---
- name: "Restart application"
  systemd:
    name: "{{ springboot_application_name }}"
    enabled: yes
    daemon-reload: yes
    state: restarted
  when: use_system_d and springboot_service_install == true
